#!/usr/bin/env python3
"""izumi web UI — serve the read-only reports dir (dashboard + JSON) over HTTP.

Zero dependencies (stdlib ``http.server``). Serves ``index.html`` (generated by the
``webdashboard`` module) plus every module's ``plan.json`` / ``summary.md`` /
``izumi.prom``. GET-only, so it is read-only by construction. Meant to run as a
small always-on container (see ``deploy/docker-compose.yml``).

    python webui.py [--dir reports] [--port 8888] [--host 0.0.0.0]

If ``--dir`` is omitted it reads ``reporting.dir`` from ``config/config.json``
(falling back to ``./reports``). stdlib-only and 3.9-safe.
"""

from __future__ import annotations

import argparse
import http.server
import json
import os
import socketserver
import sys
from functools import partial


def default_reports_dir() -> str:
    """``reporting.dir`` from config/config.json, or ``./reports`` as a fallback."""
    root = os.path.dirname(os.path.realpath(__file__))
    cfg_path = os.path.join(root, "config", "config.json")
    try:
        with open(cfg_path, encoding="utf-8") as fh:
            data = json.load(fh)
        reporting = data.get("reporting") if isinstance(data, dict) else None
        directory = reporting.get("dir") if isinstance(reporting, dict) else None
        if isinstance(directory, str) and directory:
            return directory
    except (OSError, ValueError):
        pass
    return os.path.join(root, "reports")


def _parse(argv: list[str] | None) -> argparse.Namespace:
    p = argparse.ArgumentParser(prog="webui.py", description="izumi read-only reports server")
    p.add_argument("--dir", default=None, help="reports dir to serve (default: from config)")
    p.add_argument("--port", type=int, default=8888)
    p.add_argument("--host", default="0.0.0.0")  # noqa: S104 - LAN dashboard, intentional
    return p.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = _parse(argv)
    directory = args.dir or default_reports_dir()
    if not os.path.isdir(directory):
        os.makedirs(directory, exist_ok=True)
    handler = partial(http.server.SimpleHTTPRequestHandler, directory=directory)
    print(f"izumi web UI serving {directory} on http://{args.host}:{args.port}", file=sys.stderr)
    with socketserver.TCPServer((args.host, args.port), handler) as httpd:
        try:
            httpd.serve_forever()
        except KeyboardInterrupt:  # pragma: no cover - manual stop
            pass
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
