#!/usr/bin/env python3
"""izumi web UI — serve the reports dir (dashboard + JSON) over HTTP.

Zero dependencies (stdlib ``http.server``). GET serves ``index.html`` (generated by
the ``webdashboard`` module) + the report files, read-only.

OPTIONAL interactive API (opt-in, off by default): if ``IZUMI_WEB_TOKEN`` is set, a
``POST /api/run`` with ``{"action": <name>, "token": <token>}`` runs ONE whitelisted
**read-only** module (or the ``health`` pipeline) and regenerates the panel — so the
dashboard buttons can refresh data on demand. No token → the API is disabled and the
server stays purely read-only. Only read-only actions are allowed (no apply/dbrepair);
for that the API needs the container run with the docker socket + a writable reports
mount.

Optional HTTP Basic Auth over the WHOLE panel: set ``IZUMI_WEB_USER`` + ``IZUMI_WEB_PASS``
(for exposing it beyond the LAN); unset = no auth.

    python webui.py [--dir reports] [--port 8888] [--host 0.0.0.0]

If ``--dir`` is omitted it reads ``reporting.dir`` from ``config/config.json``. Base
server is stdlib-only and 3.9-safe (the API imports the platform lazily, in-container).
"""

from __future__ import annotations

import argparse
import base64
import hmac
import http.server
import json
import os
import socketserver
import sys
from functools import partial
from io import BytesIO

_API_TOKEN_ENV = "IZUMI_WEB_TOKEN"  # noqa: S105 - env var NAME, not a secret value
# Only these READ-ONLY actions may be triggered from the web (no apply/dbrepair here).
_ALLOWED_ACTIONS = frozenset(
    {
        "health",
        "uptime",
        "dbcheck",
        "diskwatch",
        "permsdoctor",
        "backupaudit",
        "netdoctor",
        "certdoctor",
        "capacitydoctor",
        "status",
        "configcheck",
        "shadowcheck",
        "logwatch",
        "analyst",
        "metricsexport",
        "webdashboard",
    }
)


def check_request(action: str, token: str, *, expected_token: str) -> tuple[bool, int, str]:
    """Authorize a POST /api/run: token present+correct and action whitelisted (pure)."""
    if not expected_token:
        return False, 403, "API deshabilitada (define IZUMI_WEB_TOKEN para activarla)"
    if token != expected_token:
        return False, 403, "token inválido"
    if action not in _ALLOWED_ACTIONS:
        return False, 400, f"acción no permitida: {action}"
    return True, 200, "ok"


def check_basic_auth(header: str, user: str, password: str) -> bool:
    """Validate an HTTP ``Authorization: Basic`` header against user/password (pure).

    Constant-time compare. If both user and password are empty, auth is disabled
    (returns True). Used to gate the WHOLE panel when IZUMI_WEB_USER/PASS are set.
    """
    if not user and not password:
        return True
    if not header.startswith("Basic "):
        return False
    try:
        decoded = base64.b64decode(header[6:].strip()).decode("utf-8")
    except (ValueError, UnicodeDecodeError):
        return False
    got_user, _, got_pw = decoded.partition(":")
    return hmac.compare_digest(got_user, user) and hmac.compare_digest(got_pw, password)


def check_token(token: str, *, expected_token: str) -> tuple[bool, int, str]:
    """Authorize an API call by token alone (for ask/apply, which carry no action)."""
    if not expected_token:
        return False, 403, "API deshabilitada (define IZUMI_WEB_TOKEN para activarla)"
    if token != expected_token:
        return False, 403, "token inválido"
    return True, 200, "ok"


def status_snapshot(directory: str) -> dict[str, object]:
    """Machine-readable health snapshot from the metrics store (for external pulls).

    ``{ok, modules:[{module, ok, failures}], failing:[names]}`` — lets an external
    guardian fetch WHAT is wrong, not just whether the server is up.
    """
    from pathlib import Path

    from core.metrics import MetricsStore

    db = Path(directory) / "cache" / "metrics.db"
    if not db.is_file():
        return {"ok": True, "modules": [], "failing": []}
    with MetricsStore(db) as store:
        status = store.latest_status()
    modules = [
        {
            "module": str(s.get("module")),
            "ok": bool(s.get("ok")),
            "failures": int(s.get("failures") or 0),
        }  # type: ignore[arg-type]
        for s in status
    ]
    failing = [str(m["module"]) for m in modules if not m["ok"]]
    return {"ok": not failing, "modules": modules, "failing": failing}


def export_markdown(directory: str) -> str:
    """Concatenate every module's summary.md into one downloadable report (pure)."""
    from pathlib import Path

    base = Path(directory)
    parts = ["# izumi — informe consolidado", ""]
    if base.is_dir():
        for sub in sorted(p for p in base.iterdir() if p.is_dir()):
            if sub.name in {"cache", "webdashboard", "inventory"}:
                continue
            summary = sub / "summary.md"
            if summary.is_file():
                try:
                    parts.append(
                        f"\n## {sub.name}\n\n{summary.read_text(encoding='utf-8').strip()}"
                    )
                except OSError:
                    continue
    return "\n".join(parts) + "\n"


def humanize_action_result(action: str, rc: int, reports_dir: str) -> str:
    """Turn a module's exit code into a message a person can read (pure-ish).

    Prefers the module's own ``plan.json`` (configcheck-style: total/missing/
    invalid counts + per-setting keys) so the alert says WHAT is wrong, not just
    ``rc=1``. Falls back to a plain ok/incidencias message for modules without one.
    """
    from pathlib import Path

    plan = Path(reports_dir) / action / "plan.json"
    if plan.is_file():
        try:
            data = json.loads(plan.read_text(encoding="utf-8"))
        except (OSError, ValueError):
            data = None
        if isinstance(data, dict) and "missing_count" in data:
            missing = int(data.get("missing_count") or 0)
            invalid = int(data.get("invalid_count") or 0)
            total = int(data.get("total") or 0)
            if missing == 0 and invalid == 0:
                return f"{action}: todo correcto — {total} ajustes revisados ✅"
            settings = data.get("settings") if isinstance(data.get("settings"), list) else []
            miss = [str(s.get("key")) for s in settings if s.get("status") == "missing"]
            inv = [str(s.get("key")) for s in settings if s.get("status") == "invalid"]
            parts = []
            if miss:
                parts.append(f"faltan {missing}: " + ", ".join(miss))
            if inv:
                parts.append(f"inválidos {invalid}: " + ", ".join(inv))
            return f"{action}: " + "; ".join(parts)
    if rc == 0:
        return f"{action}: completado correctamente ✅"
    return f"{action}: terminó con incidencias — abre el informe en el panel para el detalle"


def _run_platform_action(action: str) -> tuple[bool, str]:  # pragma: no cover - needs the platform
    """Run a whitelisted read-only module/pipeline in-process (container only)."""
    from core import config as config_mod
    from core import registry
    from run import _run_module, _run_pipeline, build_context

    cfg = config_mod.load()
    registry.discover()
    ctx = build_context(cfg)
    if action in cfg.pipelines:
        rc = _run_pipeline(ctx, action, cfg.pipelines[action])
    else:
        rc = _run_module(ctx, action)
    return rc == 0, humanize_action_result(action, rc, str(cfg.reporting.dir))


def _ask_assistant(question: str) -> tuple[bool, str]:  # pragma: no cover - needs the platform
    from assistant import answer

    if not question.strip():
        return False, "pregunta vacía"
    return True, answer(question)


def _apply_command(command: str) -> tuple[bool, str]:  # pragma: no cover - needs the platform
    from aictx.apply import ApplyAction, apply_action, classify, finding_fingerprint

    verdict = classify(command)
    if not verdict.allowed:  # allow-list is the boundary even from the web
        return False, f"rechazado (no en la allow-list): {verdict.reason}"
    action = ApplyAction(
        command=command,
        category=verdict.category,
        finding_title="web apply",
        fingerprint=finding_fingerprint(command),
        severity="info",
    )
    outcome = apply_action(action)
    return outcome.ok, (outcome.output or outcome.error or f"rc={outcome.returncode}").strip()


_NO_INDEX_HTML = (
    b"<!doctype html><meta charset=utf-8>"
    b"<style>body{font:15px system-ui;margin:3rem;color:#333}</style>"
    b"<h2>izumi</h2><p>El panel a\xc3\xban no est\xc3\xa1 generado.</p>"
    b"<p>Ejecuta el chequeo de salud una vez:</p>"
    b"<pre>python run.py health</pre>"
    b'<p><a href="/">recargar</a></p>'
)


class _DashboardHandler(http.server.SimpleHTTPRequestHandler):
    """Serves index.html at a directory; never dumps a raw file listing."""

    def list_directory(self, path: str):  # type: ignore[override]
        # Reached only when a directory has no index.html — show a hint, not a dump.
        self.send_response(200)
        self.send_header("Content-Type", "text/html; charset=utf-8")
        self.send_header("Content-Length", str(len(_NO_INDEX_HTML)))
        self.end_headers()
        return BytesIO(_NO_INDEX_HTML)

    def _json(self, code: int, payload: dict[str, object]) -> None:
        body = json.dumps(payload).encode("utf-8")
        self.send_response(code)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def _auth_ok(self) -> bool:
        """Optional HTTP Basic Auth over the whole panel (opt-in via IZUMI_WEB_USER/PASS)."""
        if check_basic_auth(
            self.headers.get("Authorization", ""),
            os.environ.get("IZUMI_WEB_USER", ""),
            os.environ.get("IZUMI_WEB_PASS", ""),
        ):
            return True
        self.send_response(401)
        self.send_header("WWW-Authenticate", 'Basic realm="izumi"')
        self.send_header("Content-Length", "0")
        self.end_headers()
        return False

    def do_GET(self) -> None:
        if not self._auth_ok():
            return
        route = self.path.split("?", 1)[0]
        if route == "/api/status":
            self._json(200, status_snapshot(self.directory))
            return
        if route == "/api/export":
            body = export_markdown(self.directory).encode("utf-8")
            self.send_response(200)
            self.send_header("Content-Type", "text/markdown; charset=utf-8")
            self.send_header("Content-Disposition", 'attachment; filename="izumi-informe.md"')
            self.send_header("Content-Length", str(len(body)))
            self.end_headers()
            self.wfile.write(body)
            return
        super().do_GET()

    def do_POST(self) -> None:
        if not self._auth_ok():
            return
        path = self.path.split("?", 1)[0]
        if path not in ("/api/run", "/api/ask", "/api/apply"):
            self._json(404, {"ok": False, "message": "not found"})
            return
        length = int(self.headers.get("Content-Length") or 0)
        try:
            data = json.loads(self.rfile.read(length) or b"{}") if length else {}
        except (ValueError, OSError):
            data = {}
        if not isinstance(data, dict):
            data = {}
        token = str(data.get("token", ""))
        expected = os.environ.get(_API_TOKEN_ENV, "")
        try:
            if path == "/api/run":
                action = str(data.get("action", ""))
                ok, code, msg = check_request(action, token, expected_token=expected)
                if ok:
                    ok, detail = _run_platform_action(action)
                    code, msg = (200 if ok else 500), detail
            elif path == "/api/ask":
                ok, code, msg = check_token(token, expected_token=expected)
                if ok:
                    ok, detail = _ask_assistant(str(data.get("question", "")))
                    code, msg = (200 if ok else 400), detail
            else:  # /api/apply
                ok, code, msg = check_token(token, expected_token=expected)
                if ok:
                    ok, detail = _apply_command(str(data.get("command", "")))
                    code, msg = (200 if ok else 400), detail
        except Exception as exc:  # never crash the server on a handler error
            ok, code, msg = False, 500, f"No se pudo completar la acción: {exc}"
        self._json(code, {"ok": ok and code == 200, "message": msg})


def default_reports_dir() -> str:
    """``reporting.dir`` from config/config.json, or ``./reports`` as a fallback."""
    root = os.path.dirname(os.path.realpath(__file__))
    cfg_path = os.path.join(root, "config", "config.json")
    try:
        with open(cfg_path, encoding="utf-8") as fh:
            data = json.load(fh)
        reporting = data.get("reporting") if isinstance(data, dict) else None
        directory = reporting.get("dir") if isinstance(reporting, dict) else None
        if isinstance(directory, str) and directory:
            return directory
    except (OSError, ValueError):
        pass
    return os.path.join(root, "reports")


def _parse(argv: list[str] | None) -> argparse.Namespace:
    p = argparse.ArgumentParser(prog="webui.py", description="izumi read-only reports server")
    p.add_argument("--dir", default=None, help="reports dir to serve (default: from config)")
    p.add_argument("--port", type=int, default=8888)
    p.add_argument("--host", default="0.0.0.0")  # noqa: S104 - LAN dashboard, intentional
    return p.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = _parse(argv)
    directory = args.dir or default_reports_dir()
    if not os.path.isdir(directory):
        os.makedirs(directory, exist_ok=True)
    handler = partial(_DashboardHandler, directory=directory)
    print(f"izumi web UI serving {directory} on http://{args.host}:{args.port}", file=sys.stderr)
    with socketserver.TCPServer((args.host, args.port), handler) as httpd:
        try:
            httpd.serve_forever()
        except KeyboardInterrupt:  # pragma: no cover - manual stop
            pass
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
